---
output: github_document
---

Load packages
```{r message=FALSE,warning=FALSE}
suppressPackageStartupMessages(library("tidyverse"))
suppressPackageStartupMessages(library("GEOquery"))
suppressPackageStartupMessages(library("limma"))
suppressPackageStartupMessages(library("DESeq2"))
suppressPackageStartupMessages(library("edgeR"))
suppressPackageStartupMessages(library("pheatmap"))
suppressPackageStartupMessages(library("statmod"))
suppressPackageStartupMessages(library("ggrepel"))
```


```{r, warning=FALSE, message=FALSE, results='hide'}
eset <- getGEO("GSE152075", getGPL = FALSE)[[1]]
getGEOSuppFiles("GSE152075")
raw_counts <- read.csv("GSE152075/GSE152075_raw_counts_GEO.txt", sep = "")
count_mat <- as.matrix(raw_counts,row.names="gene_id")
```

```{r}

pdata <- eset@phenoData@data %>% as_tibble()
pdata_mod <- pdata %>%
  select(title, `age:ch1`, characteristics_ch1.3, characteristics_ch1.4, `sars-cov-2 positivity:ch1`) %>%
  subset(`age:ch1` != "Unknown") %>%
  transform(`age:ch1` = as.numeric(`age:ch1`))

pdata_clean = pdata %>%
  select(title, `age:ch1`, characteristics_ch1.3, characteristics_ch1.4, `sars-cov-2 positivity:ch1`)
colnames(pdata_clean) = c("Title", "Age", "Gender", "Batch", "Sars_test")

colnames(pdata_mod) = c("Title", "Age", "Gender", "Batch", "Sars_test")
pdata_mod[is.na(pdata_mod)] <- 90

pdata_mod = pdata_mod %>%
  mutate(Age_category =  case_when(
    Age < 18 ~ "Child",
    Age >= 18 & Age < 35 ~ "Young Adult",
    Age >= 35 & Age < 65  ~ "Adult",
    TRUE ~ "Senior"
  ))

data = pdata %>%
       select(title, `age:ch1`) %>% 
       subset(`age:ch1` == "Unknown")

drop <- data$title
count_mat_final  = count_mat[,!colnames(count_mat) %in% drop]
```

# Using Deseq
```{r}
sumexp <- SummarizedExperiment(assays = SimpleList(counts = as.matrix(count_mat)), 
                             colData = DataFrame(pdata_clean))

assays(sumexp)$cpm <- cpm(count_mat, log = FALSE, normalized.lib.sizes = FALSE)
sumexp
```

```{r}
keep_deseq <- which(rowSums(assays(sumexp)$cpm > 100) >= 50)
sumexp <- sumexp[keep_deseq,]

assays(sumexp)$log2cpm <- log2(assays(sumexp)$cpm + 1)
sumexp

```

```{r}
#Setting up model matrix
designMatrix1 = model.matrix(~Sars_test , data = colData(sumexp))
designMatrix2 = model.matrix(~Sars_test + Batch , data = colData(sumexp))
```


```{r}
dds1 <- DESeqDataSet(sumexp, designMatrix1)
dds1

dds1 <- estimateSizeFactors(dds1)
# double check that samples are in the same order in both edger and deseq objects
#identical(colnames(dge_disp), colnames(dds))

dds1 <- DESeq(dds1)
resultsNames(dds1)
res1 <- results(dds1)
res1 <-res1[order(res1$pvalue),]
# scatter plot of log2foldchange
plotMA(res1, alpha = 0.05)
```

```{r}
dds2 <- DESeqDataSet(sumexp, designMatrix2)
dds2

dds2 <- estimateSizeFactors(dds2)
# double check that samples are in the same order in both edger and deseq objects
#identical(colnames(dge_disp), colnames(dds))

dds2 <- DESeq(dds2)
resultsNames(dds2)
res2 <- results(dds2)
res2 <- res2[order(res2$pvalue),]
# scatter plot of log2foldchange
plotMA(res2, alpha = 0.05)
```

```{r}
#idx <- identify(res2$baseMean, res2$log2FoldChange)
#rownames(res2)[idx]
```


```{r}
full_results1 <- as.data.frame(res1)
full_results1 <- cbind(Genes = rownames(full_results1), full_results1)
rownames(full_results1) <- NULL
full_results1 <- full_results1[order(full_results1$pvalue), ]

p_cutoff <- 0.01
fc_cutoff <- 1
topN <- 20

options(ggrepel.max.overlaps = Inf)

test_sig <- full_results1 %>% 
  mutate(Significant = padj < p_cutoff, abs(log2FoldChange) > fc_cutoff ) %>% 
  mutate(Rank = 1:n(), Label = ifelse(Rank < topN, Genes,""))

test_sig %>% 
  ggplot(aes(x = log2FoldChange, y = stat, col=Significant,label=test_sig$Label)) + geom_point() + geom_text_repel(col="black")

genes_of_interest <- test_sig %>% 
  filter(Rank < topN) %>% 
  pull(Genes)

```


```{r}
full_results2 <- as.data.frame(res2)
full_results2 <- cbind(Genes = rownames(full_results2), full_results2)
rownames(full_results2) <- NULL
full_results2 <- full_results2[order(full_results2$pvalue), ]

upreg <- subset(res2, log2FoldChange > 1)

upreg <- subset(res2, log2FoldChange > 1)

full_results2_upreg <- filter(full_results2, padj < 0.05, log2FoldChange > 1)
full_results2_downreg <- filter(full_results2, padj < 0.05, log2FoldChange < -1)

p_cutoff <- 0.01
fc_cutoff <- 1
topN <- 20

options(ggrepel.max.overlaps = Inf)

test_sig2 <- full_results2 %>% 
  mutate(Significant = padj < p_cutoff, abs(log2FoldChange) > fc_cutoff ) %>% 
  mutate(Rank = 1:n(), Label = ifelse(Rank < topN, Genes,""))

test_sig2 %>% 
  ggplot(aes(x = log2FoldChange, y = stat, col=Significant,label=test_sig2$Label)) + geom_point() + geom_text_repel(col="black")

genes_of_interest2 <- test_sig2 %>% 
  filter(Rank < topN) %>% 
  pull(Genes)

```


```{r}
#get list of DE genes, then display some of up and down-regulated genes
resSig <- full_results2[ full_results2$padj < .05, ]
#up-regulated
upreg<-resSig[order(resSig$log2FoldChange,-resSig$baseMean),]
#down-regulated
downreg <- resSig[order(-resSig$log2FoldChange,-resSig$baseMean),]
```

# Using EdgeR

```{r}
dge <- DGEList(counts = count_mat, samples = pdata_clean, group = pdata_clean$Sars_test)
dim(dge)
apply(dge$counts, 2, sum) # total gene counts per sample

keep_edge <- rowSums(cpm(dge)>100) >= 50
dge_mod <- dge[keep_edge,]
dim(dge_mod)

dge$samples$lib.size <- colSums(dge$counts) # Reset library sizes
```

```{r}
#Calculating TMM normalization factors and directly adding them to the DGEList
dge_norm = calcNormFactors(dge_mod, method = "TMM")

cpm = cpm(dge_norm, log = FALSE, normalized.lib.sizes = TRUE)
log2cpm = log2(cpm + 1)

#Transforming object from wide to long format for plotting 
ran_samp <- subset(log2cpm[,150:170])

longExpr = ran_samp %>% 
           as.data.frame() %>% 
           rownames_to_column("gene") %>%
           pivot_longer(cols = !gene,
                        values_to = "Expression",
                        names_to = "sample_ID")

longExpr  %>% 
  ggplot(aes(x = Expression, color = sample_ID)) +
  geom_density() +
  labs( x = "Expression", y = "Density", title = "Density plot showing distribution of gene expression across 20 random samples")

longExpr %>% 
  ggplot(aes(x = sample_ID, y = Expression)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))  +
  labs( x = "Sample ID", y = "Gene Expression", title = "Box plot showing distribution of gene expression across 20 random samples")
```

```{r}
#Calculate correlation using log2 transformed CPM values from earlier
cormat = round(cor(ran_samp), 2)

#Plot heatmap
pheatmap(cormat, border_color = NA, cluster_rows = TRUE, cellheight=9, cellwidth = 9)
```

```{r}
#Setting up model matrix
designMatrix1 = model.matrix(~Sars_test , data = colData(sumexp))
designMatrix2 = model.matrix(~Sars_test + Batch , data = colData(sumexp))
```

```{r}
#Calculation of variance weights and generation of mean-variance trend plot
de_model1 = voom(dge_norm, design = designMatrix1, plot = TRUE)
de_model2 = voom(dge_norm, design = designMatrix2, plot = TRUE)
```

```{r}
dge_disp1 <- estimateDisp(dge_norm, designMatrix1, robust = TRUE)
range(dge_disp1$prior.df)
plotBCV(dge_disp1,  cex=0.5)

dge_disp2 <- estimateDisp(dge_norm, designMatrix2, robust = TRUE)
range(dge_disp2$prior.df)
plotBCV(dge_disp2,  cex=0.5)
```


```{r}
lfit1 <- glmFit(dge_disp1, designMatrix1)
lrt1 <- glmLRT(lfit1, coef = "Sars_testpos")
toptags1 <- topTags(lrt1)$table %>% signif(3)

lfit2 <- glmFit(dge_disp2, designMatrix2)
lrt2 <- glmLRT(lfit2, coef = "Sars_testpos")
lrt2_filter_upreg <- filter(lrt2$table, PValue < 0.05, logFC >1)
dim(lrt2_filter_upreg)
lrt2_filter_downreg <- filter(lrt2$table, PValue < 0.05, logFC < -1)
dim(lrt2_filter_downreg)
toptags2 <- topTags(lrt2)$table %>% signif(3)

```

```{r}
#write.table(as.data.frame(resSig[ order( -resSig$log2FoldChange,-resSig$baseMean ),]), file="UpRegulated.txt")
#get list of DE genes, then display some of up and down-regulated genes
resSig <- lrt2[lrt2$table$PValue < .05, ]
#up-regulated
head(resSig[order(resSig$table$logFC,])
#down-regulated
head(resSig[order(-resSig$table$logFC,-resSig$baseMean),])
```


```{r}
de1 <- decideTestsDGE(lrt1, adjust.method="BH", p.value = 0.05)
de1tags1 <- rownames(dge_disp1)[as.logical(de1)]
plotSmear(lrt1, de.tags=de1tags1)
#abline(h = c(-1, 1), col = "blue")
summary(de1)

de2 <- decideTestsDGE(lrt2, adjust.method="BH", p.value = 0.05)
de1tags2 <- rownames(dge_disp2)[as.logical(de2)]
plotSmear(lrt2, de.tags=de1tags2)
#abline(h = c(-1, 1), col = "blue")
summary(de2)
```

