---
title: "Final DE Analysis"
author: "Credo Casmil, Aditi Nagaraj Nallan, Ekpereka Amutaigwe and Dollina Dodani"  
date: '2022-03-20'
output: github_document
editor_options: 
  chunk_output_type: inline
---

# Load packages

```{r message=FALSE,warning=FALSE}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(GEOquery))
suppressPackageStartupMessages(library(limma))
suppressPackageStartupMessages(library(edgeR))
suppressPackageStartupMessages(library(pheatmap))
suppressPackageStartupMessages(library(statmod))
suppressPackageStartupMessages(library(ggrepel))
suppressPackageStartupMessages(library(ggbiplot))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(GGally))
suppressPackageStartupMessages(library(caTools)) ## used for splitting the data into training and validation sets
suppressPackageStartupMessages(library(caret)) ## used for confusion matrix, accuracy, sensitivity, and specificity
suppressPackageStartupMessages(library(mice))
suppressPackageStartupMessages(library(VIM))
suppressPackageStartupMessages(library(sva))
#suppressPackageStartupMessages(library(Glimma))

```

```{r}
## Setting work directory to save plots 
setwd(getwd())
```

```{r, warning=FALSE, message=FALSE, results='hide'}
eset <- getGEO("GSE152075", getGPL = FALSE)[[1]]
getGEOSuppFiles("GSE152075")

#Read in the count matrix
raw_counts <- read.csv("GSE152075/GSE152075_raw_counts_GEO.txt", sep = "")
count_mat <- as.matrix(raw_counts,row.names="gene_id")
```

```{r}
#Read in the metadata
pdata <- eset@phenoData@data %>% as_tibble()

#Subset the metadata to include only columns of interest
pdata_clean = pdata %>%
  select(title, `age:ch1`, `gender:ch1`, `sequencing_batch:ch1`, `sars-cov-2 positivity:ch1`, `n1_ct:ch1`)

colnames(pdata_clean) = c("Sample", "Age", "Gender", "Batch", "Sars_test", "Viral_load")

pdata_clean <- within(pdata_clean, Age[Age == "90+"] <- "90")

#Modify the subset data to create a new column of Age_categories based on the column Age 
pdata_mod <- pdata_clean %>%
  transform(Age = as.numeric(Age))

pdata_mod = pdata_mod %>%
  mutate(Age_category =  case_when(
    Age < 18 ~ "Child",
    Age >= 18 & Age < 35 ~ "Young Adult",
    Age >= 35 & Age < 65  ~ "Adult",
    Age >= 65 ~ "Senior"
  )) 

pdata_mod <- pdata_mod[complete.cases(pdata_mod), ]

#Convert all character variables of interest to factor type 
convert = c("Age_category", "Gender", "Sars_test", "Batch")
pdata_mod[convert] <- lapply(pdata_mod[convert], factor)
```

```{r}
#Examine metadata
table(pdata_mod$Gender)
pdata_mod %>% select(-Sample, -Viral_load, -Age) %>%
  ggpairs(aes(color=Sars_test, alpha=0.4), cardinality_threshold = 100)
```

```{r}
#check our two dfs are in the same order
identical(pdata_mod$Sample, colnames(count_mat))
```

```{r}
age_groups <- c(pdata_imputed$Age_category)
sex <- c(pdata_imputed$Gender)
cov_test <- c(pdata_imputed$Sars_test)

Batches = as.character(pdata_imputed$Batch)

covariate_matrix1 <- cbind(cov_test)


corrected_data1 <- ComBat_seq(counts = count_mat, batch = Batches, group = cov_test)


dim(count_mat)
dim(corrected_data1)

```

```{r}
#Creating DGE List 
dge <- DGEList(counts = corrected_data1, samples = pdata_imputed)
dim(dge)
head(apply(dge$counts, 2, sum)) # total gene counts per sample

#removing lowly expressed genes
keep_edge <- rowSums(cpm(dge)>10) >= 2
dge_mod <- dge[keep_edge,]
dim(dge_mod)

```

```{r, results='hide'}
# Reset library sizes
dge$samples$lib.size <- colSums(dge$counts) 
```

```{r}
#Calculating TMM normalization factors and directly adding them to the DGEList
dge_norm = calcNormFactors(dge_mod, method = "TMM")

#cpm and log transformation after adding a pseudo-count
cpm = cpm(dge_norm, log = FALSE, normalized.lib.sizes = TRUE)
log2cpm = log2(cpm + 1)
```

```{r}
ran_samp = pdata_imputed %>%
           group_by(Sars_test) %>%
           sample_n(size = 10)
samples = ran_samp$Sample
names.use <- colnames(log2cpm)[(colnames(log2cpm) %in% samples)]
subset_data <- log2cpm[, names.use]

longExpr = subset_data %>% 
           as.data.frame() %>% 
           rownames_to_column("gene") %>%
           pivot_longer(cols = !gene,
                        values_to = "Expression",
                        names_to = "Sample")
longExpr <- left_join(longExpr, ran_samp, by="Sample")

#Box plot
longExpr %>%
  ggplot(aes(Sample, Expression)) + 
    geom_boxplot() + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

cormat = round(cor(subset_data), 2)

#Density plot
ggplot(data = longExpr) + 
  geom_density(aes(Expression, group=Sample, group="Sars_test"), color="grey") + 
  geom_density(aes(Expression), color="black", size=1.5)

#Create annotation column for pheatmap
annotation_column = data.frame(Infection_state = ran_samp$Sars_test,
                               Age = ran_samp$Age_category,
                               row.names = colnames(cormat))
#Plot heatmap
pheatmap(cormat, border_color = NA, annotation_col = annotation_column, cluster_rows = TRUE, cellheight=9, cellwidth = 9)
```

```{r}
#Setting up model matrix
designMatrix1 = model.matrix(~Sars_test*Age_category, data = pdata_imputed) 
colnames(designMatrix1)

designMatrix2 = model.matrix(~Sars_test*Gender, data = dge_norm$samples) 
colnames(designMatrix2)

designMatrix3 = model.matrix(~Gender*Age_category, data = dge_norm$samples)
colnames(designMatrix3)
designMatrix3 <- designMatrix3[,-6]

designMatrix4 = model.matrix(~Sars_test*Gender*Age_category, data = dge_norm$samples)
designMatrix4 <- designMatrix4[, c(-11, -14)]
colnames(designMatrix4)
```

```{r}
#Estimating dispersion parameters for each tag
dge_disp1 <- estimateDisp(dge_norm, designMatrix1, robust = TRUE) 
range(dge_disp1$prior.df)
plotBCV(dge_disp1,  cex=0.5)

lfit1 <- glmFit(dge_disp1, designMatrix1)
lrt1 <- glmLRT(lfit1)
deg_1 <- topTags(lrt1, n = Inf, p = 0.05)$table
up_1 <- deg_1[deg_1$logFC > 0,]
nrow(up_1)
down_1 <- deg_1[deg_1$logFC < 0,]
nrow(down_1)


de1 <- decideTests(lrt1, adjust.method="BH", p.value = 0.05, lfc = 1)
de1tags1 <- rownames(dge_disp1)[as.logical(de1)]
de1_summary <- summary(de1)
de1_summary

par(mfrow=c(1,2))
plotMD(lrt1,status=de1[,"Sars_testpos:Age_categoryYoung Adult"], values = c(-1, 1), hl.col=c("blue","red"))

```

```{r}
#Estimating dispersion parameters for each tag
dge_disp2 <- estimateDisp(dge_norm, designMatrix2, robust = TRUE) 
range(dge_disp2$prior.df)
plotBCV(dge_disp2,  cex=0.5)

lfit2 <- glmFit(dge_disp2, designMatrix2)
lrt2 <- glmLRT(lfit2)
deg_2 <- topTags(lrt2, n = Inf, p = 0.05)$table
up_2 <- deg_2[deg_2$logFC > 0,]
down_2 <- deg_2[deg_2$logFC < 0,]

de2 <- decideTestsDGE(lrt2, adjust.method="BH", p.value = 0.05)
de1tags2 <- rownames(dge_disp2)[as.logical(de2)]
plotSmear(lrt2, de.tags=de1tags2)
de2_summary <- summary(de1)
de2_summary
```

```{r}
#Estimating dispersion parameters for each tag
dge_disp3 <- estimateDisp(dge_norm, designMatrix3, robust = TRUE) 
range(dge_disp3$prior.df)
plotBCV(dge_disp3,  cex=0.5)

lfit3 <- glmFit(dge_disp3, designMatrix3)
lrt3 <- glmLRT(lfit3)
deg_3 <- topTags(lrt3, n = Inf, p = 0.05)$table
up_3 <- deg_3[deg_3$logFC > 0,]
nrow(up_3)
down_3 <- deg_3[deg_3$logFC < 0,]
nrow(down_3)

de3 <- decideTestsDGE(lrt3, adjust.method="BH", p.value = 0.05)
de1tags3 <- rownames(dge_disp3)[as.logical(de2)]
plotSmear(lrt3, de.tags=de1tags3)
de3_summary <- summary(de3)
de3_summary
```

```{r}
#Estimating dispersion parameters for each tag
dge_disp4 <- estimateDisp(dge_norm, designMatrix4, robust = TRUE) 
range(dge_disp4$prior.df)
plotBCV(dge_disp4,  cex=0.5)

lfit4 <- glmFit(dge_disp4, designMatrix4)
lrt4 <- glmLRT(lfit4)
deg_4 <- topTags(lrt4, n = Inf, p = 0.1)$table
up_4 <- deg_1[deg_4$logFC > 0,]
nrow(up_4)
down_4 <- deg_1[deg_4$logFC < 0,]
nrow(down_4)


de4 <- decideTests(lrt4, adjust.method="BH", p.value = 0.1, lfc = 1)
de1tags4 <- rownames(dge_disp4)[as.logical(de4)]
de4_summary <- summary(de4)
de4_summary

par(mfrow=c(1,2))
plotMD(lrt4, status=de4[,"Sars_testpos:GenderM:Age_categoryYoung Adult"], 
       values = c(-1, 1), hl.col=c("blue","red"))
```


```{r}
# Convert raw counts data matrix to data frame
count_mat_mod <- count_mat %>% 
  as.data.frame() %>% 
  rownames_to_column("gene_id")

# Transform counts data to a long form for merging with metadata
count_mat_mod <- count_mat_mod %>% 
  pivot_longer(-gene_id, names_to = "Sample", values_to = "Expression")

# Join raw counts to filtered metadata. This automatically drops samples in the counts data that are not in the filtered metadata
counts_pdata <- pdata_mod %>% 
  left_join(count_mat_mod, by = "Sample")

# Transform data back to a wide format
counts_pdata <- pivot_wider(counts_pdata,
                             names_from = gene_id, 
                             values_from = Expression) %>% 
                column_to_rownames("Sample")

## Saving the gender column for future use!
gender_list <- counts_pdata$Gender

# This step is removing all columns with no variance and making  sure there are no NAs
counts_pdata <- counts_pdata[ , which(apply(counts_pdata, 2, var) != 0)] %>%
                  drop_na()

counts_pdata_pca <- prcomp(counts_pdata, center = TRUE, scale. = TRUE)
counts_pdata$Gender <- gender_list

summary(counts_pdata_pca)

str(counts_pdata_pca)

# Visualize PCA result by gender
autoplot(counts_pdata_pca, data = counts_pdata, colour = 'Gender')

```

## K-means clustering

```{r}
set.seed(234)
# Determine optimal number of clusters
fviz_nbclust(counts_pdata_scaled, FUNcluster = kmeans, method = "wss")
# Assign cluster value
k <- 3
# Scale the input data
counts_pdata_scaled <- scale(counts_pdata)
# What does the scaled data look like?
head(counts_pdata_scaled[,1:3], 10)
# Compute kmeans clustering
kmeans_result <- kmeans(counts_pdata_scaled, centers = k, nstart = 50)
# View within sum of squares of each cluster
kmeans_result$withinss
# Let's look at each cluster's composition
kmeans_resultTable <- data.frame(gender = pdata_mod$Gender,
                                 age_category = pdata_mod$Age_category,
                                 cluster = kmeans_result$cluster)
kable(kmeans_resultTable)
```

# MICE Imputation

```{r}
#Modify data to convert all "Unknown/not collected" values to NAs to feed into the imputation function
data = counts_pdata
data$Viral_load[data$Viral_load == "N/A"] <- 0
data$Viral_load = as.numeric(data$Viral_load)
levels(data$Gender)[3] <- NA

#Data Imputation
#mice_plot <- aggr(data, col=c('navyblue','yellow'),
#                    numbers=TRUE, sortVars=TRUE,
#                    labels=names(data), cex.axis=.7,
#                    gap=3, ylab=c("Missing data","Pattern"))

imputed_Data <- mice(data, m=3, method = 'pmm', seed = 500)
summary(imputed_Data)
```

```{r}
pdata_imputed <- complete(imputed_Data,5)
table(pdata_imputed$Age_category)
```

# Imputation based on Mode 

```{r}
data = pdata_mod
data$Viral_load[data$Viral_load == "N/A"] <- 0
data$Viral_load = as.numeric(data$Viral_load)
levels(data$Gender)[3] <- NA


getmode <- function(v){
  v=v[nchar(as.character(v))>0]
  uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]
}

for (cols in colnames(data)) {
  if (cols %in% names(data[,sapply(data, is.numeric)])) {
    data<-data%>%mutate(!!cols := replace(!!rlang::sym(cols), is.na(!!rlang::sym(cols)), mean(!!rlang::sym(cols), na.rm=TRUE)))
    
  }
  else {
    
    data<-data%>%mutate(!!cols := replace(!!rlang::sym(cols), !!rlang::sym(cols)=="", getmode(!!rlang::sym(cols))))
    
  }
}
data
```

