---
output: github_document
editor_options: 
  chunk_output_type: console
---

# Load packages

```{r message=FALSE,warning=FALSE}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(GEOquery))
suppressPackageStartupMessages(library(limma))
suppressPackageStartupMessages(library(edgeR))
suppressPackageStartupMessages(library(pheatmap))
suppressPackageStartupMessages(library(statmod))
suppressPackageStartupMessages(library(ggrepel))
suppressPackageStartupMessages(library(ggbiplot))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(GGally))
suppressPackageStartupMessages(library(caTools)) ## used for splitting the data into training and validation sets
suppressPackageStartupMessages(library(caret)) ## used for confusion matrix, accuracy, sensitivity, and specificity
suppressPackageStartupMessages(library(mice))
suppressPackageStartupMessages(library(VIM))
suppressPackageStartupMessages(library(sva))
```


```{r}
## Setting work directory to save plots 
setwd(getwd())
```

```{r, warning=FALSE, message=FALSE, results='hide'}
eset <- getGEO("GSE152075", getGPL = FALSE)[[1]]
getGEOSuppFiles("GSE152075")

#Read in the count matrix
raw_counts <- read.csv("GSE152075/GSE152075_raw_counts_GEO.txt", sep = "")
count_mat <- as.matrix(raw_counts,row.names="gene_id")
```

```{r}
#Read in the metadata
pdata <- eset@phenoData@data %>% as_tibble()

#Subset the metadata to include only columns of interest
pdata_clean = pdata %>%
  select(title, `age:ch1`, `gender:ch1`, `sequencing_batch:ch1`, `sars-cov-2 positivity:ch1`, `n1_ct:ch1`)

colnames(pdata_clean) = c("Sample", "Age", "Gender", "Batch", "Sars_test", "Viral_load")

pdata_clean <- within(pdata_clean, Age[Age == "90+"] <- "90")

#Modify the subset data to create a new column of Age_categories based on the column Age 
pdata_mod <- pdata_clean %>%
  transform(Age = as.numeric(Age))

pdata_mod = pdata_mod %>%
  mutate(Age_category =  case_when(
    Age < 18 ~ "Child",
    Age >= 18 & Age < 35 ~ "Young Adult",
    Age >= 35 & Age < 65  ~ "Adult",
    Age >= 65 ~ "Senior"
  )) 

pdata_mod <- pdata_mod[complete.cases(pdata_mod), ]

#Convert all character variables of interest to factor type 
convert = c("Age_category", "Gender", "Sars_test", "Batch")
pdata_mod[convert] <- lapply(pdata_mod[convert], factor)
```

```{r}
#Examine metadata
table(pdata_mod$Gender)
pdata_mod %>% select(-Sample, -Viral_load, -Age) %>%
  ggpairs(aes(color=Sars_test, alpha=0.4), cardinality_threshold = 100)
```

```{r}
# Extracting info about samples with unknown age
data = pdata %>%
       select(title, `age:ch1`) %>% 
       subset(`age:ch1` == "Unknown")

drop <- data$title

# Removing samples that have unknown age from the count matrix
count_mat_final  = count_mat[,!colnames(count_mat) %in% drop]
```

```{r}
#check our two dfs are in the same order
identical(pdata_mod$Sample, colnames(count_mat_final))
```

```{r}
dim(pdata_mod)
dim(count_mat_final)
```


```{r}
#Creating DGE List 
dge <- DGEList(counts = count_mat_final, samples = pdata_mod)
dim(dge)
head(apply(dge$counts, 2, sum)) # total gene counts per sample

#removing lowly expressed genes
keep_edge <- rowSums(cpm(dge)>10) >= 2
dge_mod <- dge[keep_edge,]
dim(dge_mod)

```


```{r, results='hide'}
# Reset library sizes
dge_mod$samples$lib.size <- colSums(dge_mod$counts) 
```

```{r}
#Calculating TMM normalization factors and directly adding them to the DGEList
dge_norm = calcNormFactors(dge_mod, method = "TMM")

#cpm and log transformation after adding a pseudo-count
cpm = cpm(dge_norm, log = FALSE, normalized.lib.sizes = TRUE)
log2cpm = log2(cpm + 1)
```

```{r}
ran_samp = pdata_mod %>%
           group_by(Sars_test) %>%
           sample_n(size = 10)
samples = ran_samp$Sample
names.use <- colnames(log2cpm)[(colnames(log2cpm) %in% samples)]
subset_data <- log2cpm[, names.use]

longExpr = subset_data %>% 
           as.data.frame() %>% 
           rownames_to_column("gene") %>%
           pivot_longer(cols = !gene,
                        values_to = "Expression",
                        names_to = "Sample")
longExpr <- left_join(longExpr, ran_samp, by="Sample")

#Box plot
longExpr %>%
  ggplot(aes(Sample, Expression)) + 
    geom_boxplot() + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

cormat = round(cor(subset_data), 2)

#Density plot
ggplot(data = longExpr) + 
  geom_density(aes(Expression, group=Sample, group="Sars_test"), color="grey") + 
  geom_density(aes(Expression), color="black", size=1.5)

#Create annotation column for pheatmap
annotation_column = data.frame(Infection_state = ran_samp$Sars_test,
                               Age = ran_samp$Age_category,
                               row.names = colnames(cormat))
#Plot heatmap
pheatmap(cormat, border_color = NA, annotation_col = annotation_column, cluster_rows = TRUE, cellheight=9, cellwidth = 9)
```

```{r}
#Setting up model matrix
designMatrix1 = model.matrix(~Sars_test*Age_category + Batch, data = pdata_mod)
colnames(designMatrix1)
designMatrix2 = model.matrix(~Sars_test*Gender + Batch, data = pdata_mod)
colnames(designMatrix2)
designMatrix3 = model.matrix(~Age_category*Gender + Batch, data = pdata_mod)
colnames(designMatrix3)
#designMatrix1 <- designMatrix1[, c(-32, -33,-36, -37, -38, -39,-42, -43, -44)]
```

```{r}
#Estimating dispersion parameters for each tag
dge_disp1 <- estimateDisp(dge_norm, designMatrix1, robust = TRUE) 
range(dge_disp1$prior.df)
plotBCV(dge_disp1,  cex=0.5)

lfit1 <- glmFit(dge_disp1, designMatrix1)
lrt1 <- glmLRT(lfit1)

deg_table <- lrt1$table

updeg <- deg_table%>%
  filter(logFC > 1 & PValue < 0.02)
nrow(updeg)

dndeg <- deg_table%>%
  filter(logFC < -1 & PValue < 0.02)
nrow(dndeg)

#Filtering for up and downregulated genes
lrt1_filter_upreg <- filter(lrt1$table, PValue < 0.05, logFC >1)
dim(lrt1_filter_upreg)
lrt1_filter_downreg <- filter(lrt1$table, PValue < 0.05, logFC < -1)
dim(lrt1_filter_downreg)
```

```{r}
#Estimating dispersion parameters for each tag
dge_disp2 <- estimateDisp(dge_norm, designMatrix2, robust = TRUE) 
range(dge_disp1$prior.df)
plotBCV(dge_disp1,  cex=0.5)

lfit2 <- glmFit(dge_disp2, designMatrix2)
lrt2 <- glmLRT(lfit2)

deg_table2 <- lrt2$table

updeg2 <- deg_table2%>%
  filter(logFC > 1 & PValue < 0.02)
nrow(updeg2)

dndeg2 <- deg_table2%>%
  filter(logFC < -1 & PValue < 0.02)
nrow(dndeg2)

#Filtering for up and downregulated genes
lrt2_filter_upreg2 <- filter(lrt2$table, PValue < 0.05, logFC >1)
dim(lrt2_filter_upreg)
lrt2_filter_downreg <- filter(lrt2$table, PValue < 0.05, logFC < -1)
dim(lrt2_filter_downreg)
```

```{r}
#Estimating dispersion parameters for each tag
dge_disp3 <- estimateDisp(dge_norm, designMatrix3, robust = TRUE) 
range(dge_disp3$prior.df)
plotBCV(dge_disp3,  cex=0.5)

lfit3 <- glmFit(dge_disp3, designMatrix3)
lrt3 <- glmLRT(lfit3)

deg_table3 <- lrt3$table

upreg3 <- deg_table3%>%
  filter(logFC > 1 & PValue < 0.02)
nrow(upreg3)

dnreg3 <- deg_table3%>%
  filter(logFC < -1 & PValue < 0.02)
nrow(dnreg3)

#Filtering for up and downregulated genes
lrt3_filter_upreg <- filter(lrt3_filter_upreg$table, PValue < 0.05, logFC >1)
dim(lrt3_filter_upreg)
lrt3_filter_downreg <- filter(lrt3$table, PValue < 0.05, logFC < -1)
dim(lrt3_filter_downreg)
```